// This file was generated by Prisma, and assumes you have installed the following:
// npm install --save-dev prisma dotenv
import { config } from "dotenv";
import { defineConfig } from "prisma/config";

// { quiet: true } evita que dotenv imprima su mensaje promocional en stdout
// — sin esto, cualquier script que capture stdout de un comando de Prisma
// (o de node -e "require('dotenv').config()") se contamina con ese texto.
config({ quiet: true });

export default defineConfig({
  schema: "prisma/schema.prisma",
  migrations: {
    path: "prisma/migrations",
  },
  datasource: {
    url: process.env["DATABASE_URL"],
  },
});
